version: '3'
services:

  app:
    container_name: app
    build:
      context: ./app-service
      dockerfile: Dockerfile
    image: digitalocean.com/php
    restart: unless-stopped
    tty: true
    env_file:
      ./app-service/.env
    working_dir: /var/www
    volumes:
      - ./app-service/src/:/var/www
      - ./app-service/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
      - webserver
    networks:
      - crudnet

  webserver:
    container_name: webserver
    build: ./webserver-service
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app-service/src/:/var/www
      - ./webserver-service/conf.d/:/etc/nginx/conf.d/
    networks:
      - crudnet

  db:
    container_name: db
    build:
      context: ./db-service
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    env_file:
      - ./db-service/.env
    command: mysqld
    volumes:
      - dbdata:/var/lib/mysql/
      - ./db-service/mysql.conf:/etc/mysql/my.cnf
    networks:
      - crudnet

networks:
  crudnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
