FROM mysql:5.6
#FROM mariadb:10.4

# ARG DB_NAME
# ARG DB_ROOT_PASS
# ARG DB_USER_NAME
# ARG DB_USER_PASS
#
# # @see https://stackoverflow.com/questions/35479475/docker-mysql-commands-within-dockerfile-using-run-error-2002/35479564
# RUN mysql -uroot -p${DB_ROOT_PASS} -e "GRANT ALL ON ${DB_NAME}.* TO '${DB_USER_NAME}'@'%' IDENTIFIED BY '${DB_USER_PASS}'";
# RUN mysql -uroot -p${DB_ROOT_PASS} -e "FLUSH PRIVILEGES";
